repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Usa la versión más reciente
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Usa la versión más reciente
    hooks:
      - id: black
        language_version: python3.9  # Ajusta la versión según tu entorno
